GET http://localhost:3333/polls/7c79d967-acbc-4683-8961-2b3ba255e6ad HTTP/1.1

###

POST http://localhost:3333/polls HTTP/1.1
content-type: application/json

{
  "title": "Which JavaScript runtime do you primarily use for your projects?",
  "options": ["Node.js", "Deno", "Bun", "Other"]
}

###

POST http://localhost:3333/polls/7c79d967-acbc-4683-8961-2b3ba255e6ad/votes HTTP/1.1
content-type: application/json

{
  "pollOptionId": "9401e53c-9f91-4773-8f58-816a73972e1e"
}
